### ISSUE TITLE
Loop when there are 2 quests

### ISSUE THREAD

**Issue by Nox-Ater** [Farigh/pokeclicker-automation#1]
Loop when there are 2 quests of "Defeat the 'dungeon-name' dungeon in 'region-name' 'number' times" and/or "Defeat 'gym-name' in 'region-name' 'number' times". He goes to each location switching from one to the other over and over again but never starts either one.

**Comment by Farigh** [comment]
Do you have a save to help reproduce this ?

**Comment by Farigh** [comment]
I did not manage to reproduce your problem, I tried many combinations:
  - Defeat [...] pokemons on route [...] + Defeat Gym [...]
  - Defeat [...] pokemons on route [...] + Defeat Dungeon [...]
  - Defeat Gym [...] + Defeat Dungeon [...]
  - Defeat [...] pokemons on route [...] + Defeat Gym [...] + Defeat Dungeon [...]
  
I never ended-up in a dead-lock situation.

Since your description suggested that you had multiple instance of the same quest type, I tried refreshing over 20 times the quests and never ended up with multiple instance of the same type.
I looked into the pokeclicker code and it seems the game implementation does not allow such case, you can only have quests of a different kind.
As a matter of fact, I tried removing every quest kind but the DefeatPokemonsQuest one and refreshing the quest in such configuration only gave me 1 quest (even I had 2 slots on the save I tried this) : 
![image](https://user-images.githubusercontent.com/11090416/173419849-e52928b8-2544-4c6c-b230-d6b2958b7bbb.png)

So I'm wandering, are you using another script in combination of mine ?

**Comment by Nox-Ater** [comment]
[[v0.9.5] PokeClickerSave.txt](https://github.com/Farigh/pokeclicker-automation/files/8895740/v0.9.5.PokeClickerSave.txt)

**Comment by Nox-Ater** [comment]
sorry is dificult send from teamviewer from my cel. this is a save with bug

**Comment by Farigh** [comment]
I could not reproduce on `Firefox 101.0.1 (64 bits)` (my main browser).

But I just tried using `Chrome 102.0.5005.63 (Build officiel) (64 bits)` and reproduced after one dungeon completion.

I'll try to figure what went wrong on this browser
