### ISSUE TITLE
Add a "Stop on shinies" button for Dungeon

### ISSUE THREAD

**Issue by akwawa** [Farigh/pokeclicker-automation#11]
`EN`
### Is your feature request related to a problem? Please describe.
I want to do the dungeon until I have caught all the shinies Pokemon.

### Describe the solution you'd like
A new button after the "Stop on" with "Stop on Shinies"

### Describe alternatives you've considered
I don't think about other any solution.

### Additional context
I have made a fork with the dev branch (up to date) and I can push the merge if you accept it.

`FR`
### Is your feature request related to a problem? Please describe.
Je veux pouvoir faire en boucle le donjon jusqu'à avoir tous les pokémon chromatiques.

### Describe the solution you'd like
Ajouter un nouveau bouton en dessous de "Stop at" avec "Stop at shinies"

### Describe alternatives you've considered
Je n'ai pas réfléchi à d'autres alternatives.

### Additional context
J'ai apportée les modifications à la branche "dev" (à jour) avec cette fonctionnalité.
Si tu acceptes, je peux pousser cette branche en PR.

**Comment by Farigh** [comment]
`EN` 
I'll see how I can implement this, it could be usefull indeed (even though the hatchery might be a better option in most cases).
I took a look at your branch and I'm not fond of having another button (since both stop condition would be redundant), I need to think about a better way to do this.

---
`FR`
Je vais voir ce que je peux faire pour mettre ca en place, ca pourrait en effet être utile (même si je pense que dans la majorité des cas, la couveuse serait une meilleure approche).
J'ai jeter un œil à votre branche et je ne suis pas super emballé à l'idée d'ajouter un autre bouton (les deux condition d'arrêt étant un peu redondantes), je vais réfléchir a une meilleur façon d'implémenter ça

**Comment by akwawa** [comment]
Another solution would be to add the possibility to click on the Pokeball to activate or deactivate the shinies, but this is not intuitive.

**Comment by Farigh** [comment]
That's what I'm considering indeed, specifying it in the tooltip

**Comment by Farigh** [comment]
@akwawa Can I have your feedback on #14 ?

**Comment by akwawa** [comment]
After my (few) tests, your commit seems to work well! Good job adn thank you to add this feature.

I wasn't lucky enough to catch a shiny pokemon with my tests but the script is still working and I will keep an eye on it.

**Comment by Farigh** [comment]
Thanks for the feedback, I merged the PR.

I had a save with the 1st dungeon with all shiny caught.
Enabling the feature while the dungeon was running did stop the dungeon at the end of it, so I consider it good enough as a test.

I also did a test with a dungeon not having all shinies and starting the dungeon with the stop on shinies enabled.
Switching to the normal catch did stop the dungeon at the end of the run as expected as well.
