### ISSUE TITLE
Improve dungeon clearance algorithm

### ISSUE THREAD

**Issue by JorgeMCSilva** [Farigh/pokeclicker-automation#124]
### Is your feature request related to a problem? Please describe.
Currently, after we unlock the preview tiles, the dungeon pathing is going through all the tiles even tho we know they are not the boss.

### Describe the solution you'd like
Initial steps:
![image](https://user-images.githubusercontent.com/809541/188008546-90ab2caf-e5ca-4a9a-b86b-a1a28ddf2cd9.png)

Dungeon End:
![image](https://user-images.githubusercontent.com/809541/188008610-8f4d408d-64e4-42bf-9a1b-5378000a71ba.png)

I think this would speed up the dungeon completeness by a lot, specially on later areas with a lot of HP and a lot of possible fights

**Comment by Farigh** [comment]
Should this be a dedicated button, or just the default behavior when `Complete as soon as the boss was found` is enabled ?
I guess this does not need a dedicated button.

**Comment by JorgeMCSilva** [comment]
I would say this should be the default because you could be doing the following:

| Boss toggle | Chests toggle | Strategy                                                          |
|-------------|---------------|-------------------------------------------------------------------|
| OFF         | OFF           | open map fight everyone but boss open chests fight boss           |
| ON          | OFF           | open map when boss is detected fight it                           |
| OFF         | ON            | open map open all chests fight boss                               |
| ON          | ON            | open map when boss is detected open all chests in view fight boss |

**Comment by ArtMatters** [comment]
It would be a bit better to path it similar to this:
![rl47AsNoHu](https://user-images.githubusercontent.com/24460209/197383087-93081bac-c4a6-4705-a50b-23006a1ca7c2.png)
This would likely require a bit more thought in order to implement though.

**Comment by lmikulla** [comment]
Instead of a fixed pattern for going through the dungeon it might be a better idea to build a small priority list to make the maximum use of freely revealed tiles from flash / opening chests.

1. Finish boss if can visit its tile & boss toggle is on
2. Visit an unvisited revealed empty tile
3. Visit an unvisited revealed treasure tile (but dont open)
4. If revealed enough treasures to reveal the dungeon: Open all of them
5. Pick a random unrevealed tile to visit
6. Pick a random revealed enemy tile to visit. 

Alternatively for nr6. could also use some very simple pathfinding to go to boss should that be revealed.

This should (especially if we mostly care about completing the dungeons as fast as possible) hit fewer enemies than fixed paths and will very efficiently explore dungeons once the flash threshold of clears has been met. Works very well in the large dungeons of the later Game areas.
