### ISSUE TITLE
Focus.Experience: does not go to the highest route that can be one-hit anymore

### ISSUE THREAD

**Issue by unproductivityfriendly** [Farigh/pokeclicker-automation#126]
### Describe the bug
Focus.Experience does not go to the highest route that can be one-hit anymore since the last update.

### Steps to Reproduce
1. Turn on Focus.Experience

### Expected behavior
I have 644,874 Click Attack and it should go on Hoenn Route 120 as previous versions. It now sends me to Kanto Route 23.

### Additional context
![image](https://user-images.githubusercontent.com/46303932/188228884-a11534d5-cad0-4e37-bee9-45ded420c0f1.png)

**Comment by Farigh** [comment]
This was caused by the Sevii Islands 456 introduction.
The current algo expects the routes to be sorted by region and thus by max health.

However, the new Sevii island raises their max health to an Hoenn level, resulting in stopping the search without considering other regions.

I'll have to change the approche on this one, I'll work on this right away.
