### ISSUE TITLE
Chest and boss can't be found, if the player interferes with the dungeon manually

### ISSUE THREAD

**Issue by akwawa** [Farigh/pokeclicker-automation#15]
### Describe the bug
In adungeon, chests are left if not discover with the script.

### Steps to Reproduce
1. Go to a dungeon
2. Start the dungeon with the script
3. Find a chest with the script (not the tile boss)
4. Stop the script (AutoFight "OFF")
5. Finish the dungeon manually
6. When all tiles are revealed, start the script (AutoFight "ON").
7. If the boss has not been found, you have an error.
8. If you have found chests manually, the script does not open them.

### Expected behavior
When I activate the script, it has to check if I'm already in a dungeon, if yes, then it looks for visible tiles and completes the dungeon.

### Additional context
Error with the boss :
```
Uncaught TypeError: Cannot read properties of null (reading 'x')
at DungeonMap.hasAccesToTile (script.min.js?v=0.9.5:31293:19)
at DungeonMap.moveToTile (script.min.js?v=0.9.5:31243:18)
at AutomationDungeon.__dungeonFightLoop (<anonymous>:207:39)
```

**Comment by Farigh** [comment]
This is not a bug per say, more a usage outside planned behavior, I switched this to enhancement

**Comment by Farigh** [comment]
What do you think would be the most suitable behavior in such case ?

Here is what I was thinking about:
If the player is at the entrance point => standard behavior
If not, look for visible tiles:
- If the boss is visible => collect all visible chests, defeat the boss and disable the feature (since the player is most likely wanting to do the path finding manually)
- if not => go to the entrance and proceed with the standard behavior

**Comment by akwawa** [comment]
I agree with this proposal.
It is a good method for now.

Maybe it will change with testing in the future, but for now it looks good.

**Comment by Farigh** [comment]
Option 1 or 2 ?

**Comment by akwawa** [comment]
Option 1 seems to be the easiest to implement (and also the least energy consuming).

**Comment by Farigh** [comment]
@akwawa I pushed #17

Can you confirm it matches your expectations ?

I took a slightly different approche, so it covers the player moving during the automation as well.

**Comment by akwawa** [comment]
The script stops all the time, even if the button is not touched.

**Comment by Farigh** [comment]
I found the problem and repushed

**Comment by akwawa** [comment]
Another problem : if you stop the script after finding the boss and restart it, the script doesn't look at the invisible tiles and will collect the visible chests as well as kill the boss.

**Comment by Farigh** [comment]
I could change that, it's not complicated.
I tried to match the actual automation behavior, but I surely can improve this part.

I'll try to implement this, I'll tell you when it's done

**Comment by Farigh** [comment]
I pushed the modification, if that's all good to you, I'll merge the PR

**Comment by Farigh** [comment]
Note that it only collects visible but not visited chest tiles in addition to the visited ones.

Not completing the dungeon entirely is a feature in this case, since the player manually interacted with the board.
It is most likely because he wanted to speed up the process (probably because the dungeon is over powered compared to his attack, or he wanted a faster completion)

**Comment by Farigh** [comment]
I added a notification in case a user interaction was detected when turning off the feature

**Comment by Farigh** [comment]
I juste added the same treatment for the boss, if the tile is visible, but has not been visited yet, it will still consider the boss to be found and collect all chest then kill the boss
