### ISSUE TITLE
Chosing which automations we want

### ISSUE THREAD

**Issue by Tyrex512** [Farigh/pokeclicker-automation#152]
Hi,

When I load my save or open a Pokeclicker tab, the script considers I want every automation on by default (and even when turning them off, after a refresh they're back on), resulting in unwanted actions, such as replacing my farm with Cheri berries or trying to unlock new berries (if I didn't turn the option off) even though I have a Chople/Babiri/Lum/Petaya set-up going on. It also tries to breed according to the breeding rules I can add, even though I already a auto-breeding script that works well, and tries to auto-dig in the underground (I don't know if the chisel use is more effficient thant other scripts' auto-underground, but I'd rather turn it on myself than it being on by default).

The main use I have for the script is the dungeon auto-fight, because the other big script I use didn't get updated for the 0.9.18 and the dungeon floors, but since it has a nice feature of moving to the next route/gym/dungeon after X clears, it's still pretty damn useful but it sadly doesn't work well with other auto-dungeon since they tend to do a bit too much, until I found this script and the dungeon auto-fight part (there's no Dijkstra's/shortest path algorithm going on if I want to loot all chests and then go to the boss, but it's not like a full clear takes so much time I can't finish the dungeon, and I'm overjoyed at finding a script combination for my purposes). The main issue here is that once the other script moves my character to the next dungeon, this script's dungeon auto-fight turns off, forcing me to check every few hours if I didn't get stuck at the entrance of the next dungeon.

All in all, the script automatizes things I don't want it to automatize because everything is turned on by default, and doesn't automatize the one thing I wish it keep automatizing.

EDIT: It seems that the auto-fight turns off randomly and not only when the other script moves to another dungeon, I can't find why it doesn't work sometimes

**Comment by Farigh** [comment]
It's really difficult to understand the problem you describe.
This script will not try to support other scripts running alongside it (it would be too much work).

I don't know why your settings donc persist when you refresh, did you disable local storage in your browser ? Do you reload your save each time you play ?

The script settings are tied to the player id (to allow multiple saves to be configured independently), this ID is not part of the pokeclicker save it self (since it needs to be unique) and is generated every time you load or create a save.

Considering the automation stopping in autofight, it's expected if your other scripts (or yourself) move the player while the automation is performing it. This was added to prevent some bugs if the player tempers with the process.

**Comment by Farigh** [comment]
About the path-finding, this would only be possible if the script exploits informations that are hidden from the player (under the fog of war).

As stated on the wiki and in the description of this script : `This script collection does not aim at cheating. It will never perform actions that the game would not allow.`.

The only thing I'll consider are optimisations such as the one suggested in  #124 that I'll gladly implemented when I got a bit more time

**Comment by Farigh** [comment]
Finally, stopping the dungeon automation when you change location is the intended behaviour.

In most case when the player moves in another location, it's because he's playing the game and moving to a new dungeon location is not necessary for dungeon completion, it might only be to talk to an NPC for example. Or just a missclick. And it seemed better for the player to have to start the automation again, rather than having to clear the dungeon he did not want to enter in the first place if he forgot to turn it off before moving.

If you're moving from dungeon to clear achievement, you could use the Focus topic. It will automatically switch to the next achievement location

**Comment by Farigh** [comment]
I'll see if I can easily add a setting in the loader to choose to disable every thing by default

**Comment by Tyrex512** [comment]
The two issues are mainly that everything is on by default (and yeah it's probably due to localStorage shenanigans since I used a script around it, but I thank you for the setting to disable everything by default) and that the auto-battle stopped randomly, but if it's an intended behaviour to avoid issues and that there's a setting in the Focus topic for dungeons achievements, I'll turn off the other scripts when farming dungeon achievements

**Comment by Farigh** [comment]
The Focus on Achievements is not configurable at the moment.

It will behave as follows:
  - 1) complete route kills achievements of the 1st region
  - 2) complete gym defeat achievements of the 1st region
  - 3) complete dungeon clear achievement of the 1st region
  - 4) start over for the next region

---

For the feature default status, I've implemented the feature, you can follow the wiki [\[EN\]](https://github.com/Farigh/pokeclicker-automation/wiki/How-to-Setup-the-UserScript) [\[FR\]](https://github.com/Farigh/pokeclicker-automation/wiki/Comment-installer-le-UserScript)
