### ISSUE TITLE
Uso incorrecto de los Oak Items cuando se tienen varias Quest activas.

### ISSUE THREAD

**Issue by Nox-Ater** [Farigh/pokeclicker-automation#18]
En mi caso ya cuento con la posibilidad de tener hasta 4 Quest activas simultáneamente pero el Script no usa todos los Oak Items necesarios para cumplir con todas las Quest al mismo tiempo.

Ademas de que hay Quest donde no usa Oak Items que ayudarían a terminar antes como por ejemplo cuando toca capturar un Pokémon Shiny, el script no decide utilizar el Oak Item Shiny Charm.

Como ejemplo especifico, he tenido Quest simultaneas que requieren de equipar los Oak Item Exp Share, Magic Ball y Amulet Coin, mas sin embargo el script no se equipa todos los Oak Items para poder avanzar en todas las Quest al mismo tiempo.

También cuando hay que realizar Quest referentes a obtener Farm Points o cosechar alguna baya en especifico, muchas veces se pierde mucho tiempo ya que el script se dedica a estar obteniendo nuevas bayas que generalmente tardan muchas horas y por lo tanto tarda mucho en completar esas Quest.

En este punto podría habilitarse la opción de saltarse cierto tipo de Quests para no desperdiciar tiempo o modificar la opción de Auto Quest para que la Granja se mantenga disponible mientras esta activada la opcion de Auto Quest.

(Una disculpa por hacer mi reporte en español pero ya que mi dominio sobre el ingles no es muy bueno y era demasiado largo lo que quería decir ^^)

**Comment by Farigh** [comment]
Sorry I don't speak Spanish, can you describe your problem, either in French or in English please ?

**Comment by Farigh** [comment]
What I understood of you problem using google translate:

1) You would want the quest completion algorithm to determine which oak item to equip when there are multiple quests asking for those.
Do you have any example of such case ? Except for the shiny, for which I could indeed equip the charm, I can't figure out what other cases can occur (the game only gives you one quest of a given type at the same time).

2) About the farm suggestion:
The quest completion algorithm will automatically choose the lowest riping time berry to avoid such cases.
I could add a feature to skip some quests, but it's not planned for now (since it requires a lot of work, for a non-essential feature)

**Comment by Farigh** [comment]
I created #19 ans #20 to address those suggestions independently, fill free to complete those or to open another issue.
