### ISSUE TITLE
BUG - Script doesnt start

### ISSUE THREAD

**Issue by linkdest** [Farigh/pokeclicker-automation#245]
With the new updates, the script doesnt load. some part of the menu load, but it's bugged. That's the error.

Uncaught TypeError: this.__internal__unlockStrategySelection.at is not a function
    at Function.__internal__addGen3UnlockStrategies (<anonymous>:933:73)
    at Function.__internal__buildUnlockStrategySelection (<anonymous>:650:14)
    at Function.initialize (<anonymous>:33:18)
    at Function.<anonymous> (<anonymous>:72:31)

**Comment by Farigh** [comment]
Hum, this should be an engine incompatibility.
What platform are you playing on, so I can make sure to fix every problem?

**Comment by Farigh** [comment]
@linkdest I've tryed on both my browsers : 
  - FireFox 109.0.1 (64 bits)
  - Chrome 109.0.5414.120 (Build officiel) (64 bits)
And the pokémon desktop app, and I can't reproduce your problème.
You might just need to update your browser to the latest version since the Array.at() method got introduced in 2022

Here is the browser support from the [Mozilla pages](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array/at) : 
![image](https://user-images.githubusercontent.com/11090416/216596367-98016673-00d9-453a-ad1f-37a55e28f4e7.png)

**Comment by linkdest** [comment]
It works perfectly with chrome and firefox. The bug was in the client. I deleted the %app% folder and reinstalled everything. It looks like that i was using an old version of the aspp.asar. Now everything is working as supposed. 
Going to close the issue since it's solved.

**Comment by Farigh** [comment]
Perfect, thanks for the feedback 🙂

I'd advise you to get the installer I provide instead of overriding the official client app.asar (Which was the old way, before I started generating an installer)
