### ISSUE TITLE
Shiny

### ISSUE THREAD

**Issue by 0tobi** [Farigh/pokeclicker-automation#319]
### Describe the bug
I'm playing PokéClicker since 2days with the desktop script and every new shiny I encounter it seems that they aren't getting caught unless i'm very unlucky (with ultra ball + magic ball lvl 4)

### Steps to Reproduce

Idk play the game with default Poké Balls filter

### Expected behavior
Catch the shinies :(

### Additional context
Everything said in description of the bug

**Comment by Farigh** [comment]
I believe that you are indeed unlucky.

You can check the in-game `Log Book` to see if the capture filters work properly.
You should either seen `CAUGHT` or `ESCAPED` lines in it if the filter indeed tried to catch a shiny: 
![image](https://github.com/Farigh/pokeclicker-automation/assets/11090416/c8674c5b-08ca-4207-bf09-59e7849edfd4) 

If you do not find such line, then your filters might be ill-configured.
You can check which condition is met by the filter by hovering the `?`
![image](https://github.com/Farigh/pokeclicker-automation/assets/11090416/83ec7eb6-faa6-46b6-94fd-a870790b26c8)

This is unlikely an automation problem, since the automation only adds an additional filter that complement the existing ones, and does not temper with the other filters.

**Comment by 0tobi** [comment]
Well, at the time I wrote the issue I checked the log but no log for the "escaped", but I guess that messing with the filters made it work again.

**Comment by Farigh** [comment]
It might be an issue on the game's end then.
I'm glad it works again anyway.
