### ISSUE TITLE
Pinkan Berry

### ISSUE THREAD

**Issue by Flywalker753** [Farigh/pokeclicker-automation#344]
I've been stuck with unlocking the pinkan berry for about a week now.
The script only plant 3 berries and not the others show in the strategy preview
<img width="706" alt="Farm bug" src="https://github.com/Farigh/pokeclicker-automation/assets/54818057/e6d02fd4-3b68-43c3-adb6-99ba8a1d47a3">
I have all the berries required in good quantity
Is there something that i do wrong or is it a bug ?

**Comment by Farigh** [comment]
Hi,

Have you tried to shovel all plots before turning the feature one ? This might be a limitation of the implementation.
Also, did you exit the browser at any point ? The crops are still aging while you're away and this might put you past the next step of the automation.

Looking at your screenshot, you're settup looks good to me, since it will plant the berries at the right time to make them bloom at the same time (to maximize the mutation windows).

Here are the steps for the Pinka berry :

![1](https://github.com/Farigh/pokeclicker-automation/assets/11090416/ba36671b-480a-4260-8b97-9d6f8871a849)

![2](https://github.com/Farigh/pokeclicker-automation/assets/11090416/87e18dab-754b-43cb-bda5-fe9be7da6ffa)

![3](https://github.com/Farigh/pokeclicker-automation/assets/11090416/56694e1c-51a9-499e-9940-f15d1694a47f)

![4](https://github.com/Farigh/pokeclicker-automation/assets/11090416/0342ec12-72b6-4efd-892d-c76072800076)

![5](https://github.com/Farigh/pokeclicker-automation/assets/11090416/92b89297-0945-46bc-a6cb-ad6009b23847)

![6](https://github.com/Farigh/pokeclicker-automation/assets/11090416/9f134372-28b1-4765-9e03-ce3e6d7a46c1)

![7](https://github.com/Farigh/pokeclicker-automation/assets/11090416/ccc60a01-d9a0-4065-829c-d9a4e14c2fd5)

**Comment by Farigh** [comment]
I tried it on one of my saves and I have the expected behaviour after a few in-game hours : 
![image](https://github.com/Farigh/pokeclicker-automation/assets/11090416/4362837a-7bd7-409c-be67-7e5e88dc6884)

FYI, here are the ripping time of each berry : 
Watmel => 04:36:00
Magost => 04:00:00
Qualot => 01:20:00
Mago => 00:06:10
Nanab => 00:04:10
Persim => 00:01:30
Pecha => 00:01:00

The Magost will be planted when the ripe time of the Watmel goes under 4:00:00
The Qualot, when the ripe time of the Watmel goes under 1:20:00
And so on....

**Comment by Flywalker753** [comment]
Thank you very much for this detailed answer
I shoveled everything and restard the automation but it doesnt plant the Qualot 
<img width="711" alt="image" src="https://github.com/Farigh/pokeclicker-automation/assets/54818057/f4adab9b-5fa7-42c7-842a-d645d30fddc0">
I tried it on my browser and desktop app, it might be my save that is corrupt or something like that :(
Sorry for the bother

**Comment by Farigh** [comment]
Can you send me your save (you can upload it directly to your message via drag-n-drop) so I can take a look at the issue ?

**Comment by Flywalker753** [comment]
[Farm problem.txt](https://github.com/Farigh/pokeclicker-automation/files/14370691/Farm.problem.txt)
Here it is ! Thank you for taking the time :D

**Comment by Farigh** [comment]
On the provided save, you have a Shuca berry planted in the middle, instead of a Watmel.

It might have been caused by your oak item setup, because the Squirtbottle increases berry mutation chances.
You should try unequipping it

**Comment by Flywalker753** [comment]
<img width="603" alt="image" src="https://github.com/Farigh/pokeclicker-automation/assets/54818057/72bbd908-4b59-4aef-aea0-230a8f0cb78f">
I did what you said and it seems to work !
Sometimes when it mutates i have to shovel everything and restart it but its a nice improvement haha
Its been 2 days and no luck so far but i dont lose hope !
Thank you
