### ISSUE TITLE
New update [0.10.23]

### ISSUE THREAD

**Issue by MatPietrzyk** [Farigh/pokeclicker-automation#386]
New update introduced a rework of underground, also some other systems stopped working such as going to zones in trivia section etc.

**Comment by cfedey** [comment]
I noticed on one of my saves that the trivia section broke, but on the others it worked fine. So I tried just reloading the save with the broken trivia section and it worked. Not sure what ended up breaking it initially, but try reloading the save to fix it as a workaround.

As far as I can tell, everything seems to be working except automation of the new underground, barring the trivia section breaking sometimes.

**Comment by MeZmYk** [comment]
I've continued using the script since the update, and here are the issues I've noticed with the fuctions since the changes.

- Autominer does not work. Unsurprising, as it's an entirely new system.
- Focus on: Experience, Money, DT, Pokerus all work as intended. Quests is inconsistent leaning into outright broken (I have gotten it to work randomly with no understanding why it worked that time and not others). Gems works as intended. I have no data on achievements or Shadow purify, since I've already completed all tasks related to those.
- Hatchery works as intended.
- Farming works as intended.
- Autoshop works as intended, I'm pretty sure? I'm pretty sure that it's working as I've got it set up, but I've had some inconsistency at first that seems to have disappeared.
- Auto Upgrade Oak items works as intended. No data on Gems, but I expect that it is broken because of the menu change.
- Trivia: Inconsistent, on the same save I've had it work sometimes, and other times it just doesn't.

**Comment by Farigh** [comment]
I've disabled the mining feature completely, it should work fine now.

The trivia inconsistencies might have been caused by the Underground automation interfering.
Please reopen this issue if any problem related to the new update are still occurring
