### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by yrogypor** [Farigh/pokeclicker-automation#43]
Sorry for the bad title. I just tested your script and really like it. It was one of the best. I used many scripts and wrote (badly). 

Here are  many suggestions. And I dont know if you will only do automation or will change some variables of the game.

- Option to have no delay capture
- Have a shop that contain all items. It could be divided by categories (One with pokeballs/battle items, other with evolution items, farm stuff).
- The quest one activate all of them. One tip is looking for the route kill first and them select the pokeball, so you can do both at the same time. Create a menu for quests you don't want to do or put a custom timer to autorefresh.
- Farming Script: An option to harvest 1s before dying to maximize wander chance.  Some fluffy stuff would be having preset formations to unlock plots or berries.  Here is a guide of the best setups to unlock plots (https://docs.google.com/document/d/1TE5cAKSlA7TAliA001_mIiO1odZ6e4yUEMre0GBW1to/edit). The wiki has for the berries. 
- The exp focus option could read if the auto attack is on or off to decide the road to go. So it can go to the highest you can 1shot
- The gold option always go to blaine, even being able to shot champions of another region.
- When I'm doing my achievements, I let route for last to get the most DT possible. I do gyms, all dungeons I can do and do the routes, when finish a route, I check if I can get another dungeon achievement.  I made a spreadsheet to see what place I should go that gives me the most %/DT. I was thinking about doing a script that do in that order and check if I can one shot the dungeon. But I gave up because the code would be huge and I don't have that much knowledge.
- An autobuy pokeballs. Buy X balls when hit Y threshold

**Comment by yrogypor** [comment]
Played Kanto again to fully test the script. It's even better than I thought. Some other improvements:

- Now I saw that you already have an open farm option. I would improve two things: Check if field is empty before doing the farm setup. It can mess when the plants have more time to rip. And use a delay to all plants rip at the same time.
-  Gems usage is more efective going from imune to very strong. Another option is putting the points on normal, because it's the most commom type
- Did a poison gem quest and it went to sabrina. I couldn't one shot her, I had was better to go to a route that i could one click kill. The priority should be One click gym and route, than one shot gym and route. 
- I used the DT focus and it moved to route 25, where I got 70-110pokedolars. It's better to buy pokeballs than buy ultraballs and going to a gym after. My suggestion is buying the pokeball that the price is close or cheaper than the route you are.
- Hatchery using the select preference on the game, or at least the favorites. Because you could be breeding for a gym and some types are not the best option.
- Some people really dislike the safari. One way to automate it is making the user put Ash on the grass and make small horizontal movements to look for the pokemon and throw pokeballs when it's not a caught pokemon.

mb for the wall of text. The script is already great and I saw on reddit that you were looking for feedback, so I wrote everything I could think of.

**Comment by Farigh** [comment]
I'm glad you appreciate my work :)

Let me try to address all you suggestions (I'd prefer separate issues next time).

>     * Option to have no delay capture
>     * Have a shop that contain all items. It could be divided by categories 
>       (One with pokeballs/battle items, other with evolution items, farm stuff).
As stated in the wiki Home page:
```
This script collection does not aim at cheating.
It will never perform actions that the game would not allow.
```
So I wont consider implementing any of those.

---

>     * The quest one activate all of them. One tip is looking for the route kill first and them
>        select the pokeball,  so you can do both at the same time. 

I'm not sure that I understand this suggestion. Could you add more context ?

---

>     Create a menu for quests you don't want to do or put a custom timer to autorefresh.

This is already a requested feature : #20

---

>     * Farming Script: An option to harvest 1s before dying to maximize wander chance.  
>       Some fluffy stuff would be having preset formations to unlock plots or berries. 
>       Here is a guide of the best setups to unlock plots (https://docs.google.com/document/d/1TE5cAKSlA7TAliA001_mIiO1odZ6e4yUEMre0GBW1to/edit). The wiki has for the berries.

As you've guessed in your 2nd comment, it is exactly what the 'Auto Unlock' feature is doing, it handles all berries up to Gen 5 (so currently all of them). 

---

>     * The exp focus option could read if the auto attack is on or off to decide the road to go. 
>        So it can go to the highest you can 1shot

I've created a dedicated issue (#44) to implement this behavior. It could indeed be useful (although I doubt many users would turn off auto-click)

---

>     * The gold option always go to blaine, even being able to shot champions of another region.

It actually takes the gym that would give you the most money per game tick, including both click and pokemon attacks.

---

>     * When I'm doing my achievements, I let route for last to get the most DT possible. 
>       I do gyms, all dungeons I can do and do the routes, when finish a route, 
>       I check if I can get another dungeon achievement. 
>       I made a spreadsheet to see what place I should go that gives me the most %/DT. 
>       I was thinking about doing a script that do in that order and check if I can one shot the dungeon. 
>       But I gave up because the code would be huge and I don't have that much knowledge.

I'm not sure it would be the most efficient way in mid/late-game. Maybe I could do the 10.000 route-kill last but I'm not sure it's worse the effort ....

---

>     * An autobuy pokeballs. Buy X balls when hit Y threshold

I've been using a similar feature on it's own for this, I did not put it in the script-suite for now.<br>
I've created a dedicated issue for this suggestion (#45)<br>
I added the code I use as a comment.

---

>     * Now I saw that you already have an open farm option. 
>        I would improve two things: 
>        Check if field is empty before doing the farm setup.  It can mess when the plants have more time to rip. 

I'm not sure to understand this suggestion, can you elaborate a bit ?

>        And use a delay to all plants rip at the same time.

I did not really bother with this since, in most case, it won't be a problem since it allows to far some farm-point along the way.<br>
I does not seam worse the effort.

---

>     * Gems usage is more efective going from imune to very strong. 
>       Another option is putting the points on normal, because it's the most commom type

I could start with the normal type before the others, then sort by the order you suggest.<br>
However, in the long run, the script will always picks the cheapest it can buy, so I'm not sure it would really change a lot the behavior.<br>
I've added a dedicated issue to sort this out (#46).

---

>     * Did a poison gem quest and it went to sabrina. 
>        I couldn't one shot her, I had was better to go to a route that i could one click kill. 
>        The priority should be One click gym and route, than one shot gym and route.

In most cases the gym will give the player way more gems, I can however check both option and take the one that gives the most gems/game tick.<br>
I've added a dedicated issue (#47).

---

>     * I used the DT focus and it moved to route 25, where I got 70-110pokedolars. 
>        It's better to buy pokeballs than buy ultraballs and going to a gym after. 
>        My suggestion is buying the pokeball that the price is close or cheaper than the route you are.

It's a very early game problem, I'm not sure it's worse addressing as-is.<br>
I could however pick lower-tear balls if the player has some.<br>
Do you think it would be acceptable?

---

>     * Hatchery using the select preference on the game, or at least the favorites. Because you could be breeding for a gym and some types are not the best option.

Seems like a speed-runner need more than a common player need but why not.<br>
I've added a dedicated issue  (#48).

---

>     * Some people really dislike the safari. 
>       One way to automate it is making the user put Ash on the grass and make small horizontal 
>       movements to look for the pokemon and throw pokeballs when it's not a caught pokemon.

It's such a one-shot experience that I did not really thing about automating this ...<br>
I'm not sure I'll put some work into it anytime soon, but I created a dedicated issue for this (#49)

**Comment by yrogypor** [comment]
Hey, thanks for answering. I thought about creating issues, but I would spam the repo.

>I'm not sure that I understand this suggestion. Could you add more context ?

For exemple: You have 10+lvl quest and have a capture and route kill. It's better to go to the first and kill/capture at the same time. The route priority is currently one of the lowest.

>It actually takes the gym that would give you the most money per game tick, including both click and pokemon attacks.

It was because I was playing on a save without clicking. Tested on another save and worked perfectly.

>I'm not sure to understand this suggestion, can you elaborate a bit ?

I let the farm bot doing its thing. I realize that the plant was mutating because one was riping when the other one was withering.  Eventually they would get rip at the same time, but I think would be good to put a check a empty plot before starting the mutation setup.

>However, in the long run, the script will always picks the cheapest it can buy, so I'm not sure it would really change a lot the behavior.

Sure, it's because it's more efficient to buy the low multiplier first.  0.5->0.7 is a better increase than 1->1.2 even thought the multiplier being lower.

>Seems like a speed-runner need more than a common player need but why not.

I said that thinking about my AC save. It's fine not using the filter, I think adding the regional debuff is more important. When you move to johto or sinnoh, the other regions pokemons are useless, maybe only gyarados isn't.

>It's such a one-shot experience that I did not really thing about automating this

I agree. It take at max 20min and only once.
